# Generated by Django 4.2.2 on 2023-09-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_purchasebills_purchasebillitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_bills',
            name='vendor_gst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
